glints-dev/glints-aries

package.json
yarn.lock

Issue: `https://github.com/glints-dev/glints-aries/issues/18`

refactor(package): move react-dom into dev & peer dependencies, upgrade to react v16.5.2

---

src/Style/General/ButtonStyle.js

When using styled-components v4, this error appears:
Error: It seems you are interpolating a keyframe declaration (ihrlXY) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper (see https://www.styled-components.com/docs/api#css), which ensures the styles are injected correctly.
Since the `css` helper is already available with v3, use it first without needing to upgrade styled-components in this project to v4.

General: Wrap keyframes interpolation with `css` template processor.

---

src/Style/GlintsContainerStyle.js

The current rules break icon fonts from other sources, like Semantic UI. We should just ask consumers of Aries to inherit font families, instead of imposing styles on consumers.

Don't override font and box model across all descendants.

---

src/Application/JobCard/JobCard.js

Trello card: https://trello.com/c/kPDosHcu/2917-redirection-of-job-card-to-job-details-shouldnt-be-render-the-whole-page-reported-by-chong-an
Removed default property for `target` as it causes the page redirect on click

JobCard: Remove default prop `target` to leave it undefined when not provided

---

src/General/ProfilePicture/ProfilePicture.js
src/Input/Textarea/Textarea.js

Actual Results: Cursor in textarea bounced to the end of input text after 2 character inputs, if we start typing in the middle of the text.
Expected Results: Typing to continue in the middle of the text.
Cause: Suspected that the textarea component was unloaded and reloaded multiple times.
Fix: Modified the handleChange handler to return onChange directly instead of a function; Changed textArea to a pure component, so as to minimize re-rendering.

Fixed text area bug

---

src/Style/General/ButtonStyle.ts

Changed the `active` color of the `PrimaryBtn` to white.

ButtonStyle: Add active color for `PrimaryBtn`

---

src/Display/Progress/Progress.tsx
src/Style/Display/ProgressStyle.ts
stories/Display/ProgressStory.tsx

- `content`: sets the content inside the component
- `percentageRange`: sets the percentage range to display a different color on the progress component when the percentage changes
- `size`: sets the size of the component

Progress: Extend functionality with new props

---

src/Input/AutoComplete/AutoComplete.tsx

Due to this bug, selecting a country in job preferences for a recruiter
by clicking on the country was not possible, however pressing enter on
the country was working.
See https://github.com/glints-dev/glints-aries/blob/6080eddc42b9af7aaa6e4cef4b216b448c38e152/src/Input/AutoComplete/AutoComplete.tsx#L128 (L128-L129) for the correct logic which was existing for the enter keypress.
Trello link: https://trello.com/c/9p4cP9UA/3322-recruiter-unable-to-save-work-location-preferences-reported-by-duc

AutoComplete: Fix ActiveItemElement selection logic.

---

src/Input/Select/Select.tsx
src/Input/Select/SelectList.tsx
stories/Input/SelectStory.tsx

- Fix infinite loading bug when no options are returned
- Refactor `SelectList` into separate component
- Add `noOptionResult` prop in `SelectStory` and simplify the usage example

Hotfix/select infinite loading bug and refactor <Select> component

---

src/Style/Input/OmniSearchStyle.ts

Fixes: #94 
Removed the white gap after Go! button.
Before:
After Changes:

Remove unexpected gap after Go! button

---

src/General/Alert/Alert.tsx

Fixes: #97 
The Alert Box works according to the current value of the autoClose instead of taking the previous one.

Fix rendering of Alert Box when autoClose changes dynamically

---

src/Style/Navigation/BreadcrumbStyle.ts

1. In the active BreadCrumb item : Colour changed to grey and the cursor changed to default.
2. For the non active ones: Colour changed to Black.
To view the changes after installing the project :
In the file ` BreadcrumbStory.tsx ` , change the active Breadcrumb Item to div. (For now the active element is written in anchor tags which makes the cursor to be pointer by default.)
Fixes: #95

Fix the unexpected behavior of BreadCrumb

---

src/Input/Select/SelectList.tsx

- Use of data-classname led to displaying the wrong active state of SelectItem
- data-id is used because each SelectItem should be unique to determine the active state

Select: Change data-classname to data-id

---

src/Display/Tabs/TabPane.tsx
src/Display/Tabs/Tabs.tsx
src/Style/Display/TabsStyle.ts

- add props on Tabs to allow devs to set the activeTab and the onTabClick behaviour
- add label prop on children to set the label when it is passed to TabPane
- adjust tab index to allow users to press tab key to switch focus of tabs
- adjust tab index to allow users to press enter to switch to a tab in focus

Tabs: Refactor to function component with hooks and adjust tab index to allow for changing tabs with tab key

---

src/General/Badge/Badge.tsx
stories/General/BadgeStory.tsx

https://github.com/glints-dev/glints-aries/issues/119
- Change the type of label to string or number
- Only hide the badge when label is null or undefined

Badge: Fix bug where a label of 0 causes the badge not to show

---

src/Display/Tabs/Tabs.tsx

Restore the previous classNames so that the current code is not disturbed.

Tabs: Restore the previous classNames

---

src/Display/Progress/Progress.test.tsx
src/Display/Progress/Progress.tsx
src/Display/Progress/__snapshots__/Progress.test.tsx.snap
src/Style/Display/ProgressStyle.ts

Updated unit test 
- standardize to use `it` rather than `test`
- renamed some tests
- added tests case for `percentage=NaN`
Fixed bug https://github.com/glints-dev/glints-aries/issues/87

<Progress> Update unit test and fix bug 

---

src/Display/Tooltip/Tooltip.tsx

- Add onTouchStart and onTouchEnd props as a workaround for to…oltip not closing on iOS devices

Tooltip: Workaround for Tooltip not closing on iOS

---

stories/StorybookComponent.tsx

This import statement was causing  a type error:
```
import jsxToString from 'jsx-to-string';
```
```
ERROR in /home/francis/aries/glints-aries/stories/StorybookComponent.tsx(2,25):
TS7016: Could not find a declaration file for module 'jsx-to-string'. '/home/francis/aries/glints-aries/node_modules/jsx-to-string/lib/index.js' implicitly has an 'any' type.
Try `npm install @types/jsx-to-string` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsx-to-string';`
Version: typescript 3.5.1
```
Changed the import statement to a require statement instead to workaround the issue.
https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

StorybookComponent: Change import statement to require to workaround typescript error

---

src/Input/Checkbox/Checkbox.test.tsx
src/Input/Checkbox/Checkbox.tsx
src/Input/Checkbox/__snapshots__/Checkbox.test.tsx.snap

- Refactor to use hooks 
- Add unit and snapshot tests
Note: I wanted to test the `:before` and `:after` pseudo-elements to make sure that the checkbox exists. However I couldn't find a good way to do it because the `renderer` does not tell us anything about pseudo-elements. 
https://stackoverflow.com/questions/54950000/test-for-pseudo-class-using-jest-and-react-test-renderer
I tried using `getComputedStyle` but that didn't seem to work for the same reason https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

Checkbox: Refactor to use hooks and add unit and snapshot tests

---

src/Display/Modal/Modal.test.tsx
src/Display/Modal/Modal.tsx
src/Display/Modal/__snapshots__/Modal.test.tsx.snap

Fix for https://github.com/glints-dev/glints-aries/issues/91
Previously, the modal would close if a `mousedown` event occurred inside the modal, but the `mouseup` event occurred outside. This causd the modal to close when a user clicks inside the modal to copy some text, but releases the click outside the modal.
We fixed this by checking if the`mousedown` event occurred inside the modal, and ignoring the subsequent `click` event.

Modal: Do not close modal if mousedown occurs inside modal but the subsequent mouseup occurs outside it

---

src/Application/Gallery/Gallery.tsx
stories/Application/GalleryStory.tsx

For the number of images shown at once while using the Gallery component, the user should be able to pass that as a value. And the default one is set to 8 (as per the current implementation).
When the number is set to 3:

Gallery: The number of images displayed at once to be dynamic

---

src/Display/Slider/Slider.tsx

- React.Children.count will count `null` values by default which leads to bugs in the component
Note: This LOC is repeated a lot
```
const childrenCount = React.Children.toArray(children).filter(
child => !isNil(child)
).length;
```
I did not refactor it to use state or to exists as a class property because I think it is unnecessary and may introduce more bugs in the future.

Slider: Replace React.Children.count to remove null values

---

src/General/Icon/Icon.tsx
stories/General/IconStory.tsx

Previously, devs would have to create wrapper components to style the Icon. E.g.:
```
<IconWrapper>
<GlintsAriesIcon />
</IconWrapper>
```
Added props to fix this issue and allow for better customization.
- width, height, className, onClick

Icon: Add more props to increase customizability

---

src/Input/Select/__snapshots__/Select.test.tsx.snap
src/Style/Input/SelectStyle.ts

Fix for #186 
This will ensure that the options take up as much space as they need when the available width is low while growing them to match the input if there is a lot of space.
Letting them be bigger than the input is okay because the options are floating anyway.
This can be visually tested by applying the following patch and looking at the Select story:
```
diff --git a/stories/Input/SelectStory.tsx b/stories/Input/SelectStory.tsx
index 619f854..8a9c9c6 100644
--- a/stories/Input/SelectStory.tsx
+++ b/stories/Input/SelectStory.tsx
@@ -134,7 +134,7 @@ const SelectStory = () => (
<Select.Option value="software engineer">Software Engineer</Select.Option>
</Select>`}
>
-    <div style={{ width: '300px' }}>
+    <div style={{ width: '60px', border: '1px dotted black' }}>
<Select …
```

Select: Use min-width over width for options

---

src/Display/Modal/Modal.test.tsx
src/Display/Modal/Modal.tsx

In some cases the onClose function is being called even when the modal is already closed.
For instance, this can happen because the escape event listener does not get unregistered when the modal closes. This is a bug but I've decided to treat the symptom rather than the root cause because this component will likely get rewritten soon anyway.
I tried fixing the root cause before in https://github.com/glints-dev/glints-aries/pull/220 but the state management of Modal is more complex than I realized at first. A more thorough redesign of this component's API will be necessary to define the desired behavior and implement it, with or without the internal state.

Modal: Don't Call onClose When Closed

---

src/Input/Select/Select.test.tsx
src/Input/Select/Select.tsx
src/Style/Input/SelectStyle.ts
stories/Input/SelectStory.tsx

This adds properties `error` and `CustomError` to Select. When `error` is set to `true`, the Select will behave just like when setting `status` to `error`. When set to a string, the message will be displayed below the Select. By default, the message will be shown in a `span` with red text color, but supplying a `CustomError` component will render the message inside the `CustomError` instead.
This will be useful for unifying the behaviour in the frontend and will allow us to revert the Selects in the profile page modals back to the Glints Aries Select.

Select Errors

---

src/Input/TextField/index.ts

- `export { Props as TextFieldProps };` was causing the webpack build to fail when we migrated to Next.js
- Fixed it by refactoring to `export type TextFieldProps = Props;`
Related issue: https://github.com/babel/babel/issues/8361

TextField: Refactor export statement for TextFieldProps

---

.babelrc.js
package.json
yarn.lock

Some `aries` components are failing the re-hydration process and produce a react warning: `className` mismatch between server and client. This PR adds the plugin `babel-plugin-styled-components` to `.babelrc` to fix this problem. Tested on local build.
https://styled-components.com/docs/tooling#serverside-rendering

added SSR support

---

src/General/Button/Button.test.tsx
src/General/Button/Button.tsx
src/General/Button/DefaultButton.tsx
src/General/Button/GhostButton.tsx
src/General/Button/LinkButton.tsx
src/General/Button/PrimaryButton.tsx
src/General/Button/SecondaryButton.tsx
src/General/Button/__snapshots__/Button.test.tsx.snap
src/Input/SearchFilter/__snapshots__/SearchFilter.test.tsx.snap
src/Style/General/ButtonStyle.ts
stories/General/ButtonStory.tsx

Adds a property 'tag' to all Button components. When specified, the button will render as the specified tag. I chose the name 'tag" because react-intl uses the same name.
Closes #83

Render Button as Configurable Tag

---

src/Display/Tabs/TabPane.tsx
src/Display/Tabs/Tabs.tsx
src/Navigation/Dropdown/Dropdown.tsx

Fixes: #232 
For the following components, on adding className="class-name" the property wasn't set and the style couldn't be manipulated through it:
1. Tabs.Pane
2. Dropdown.Item

Tabs.Pane and Dropdown.Item: Add the classname property to these components

---

src/Style/General/AlertStyle.ts

Currently for the Alert component clicking on the area below the close icon results in closing of the alert box. This is caused by the `div` wrapping the icon taking up the height of its parent.
Fixes (only for the desktop) : #158

Alert: Fix the closing of the alert on clicking below the close icon

---

src/Input/NumberInput/__snapshots__/NumberInput.test.tsx.snap
src/Input/TextField/TextField.test.tsx
src/Input/TextField/TextField.tsx
src/Input/TextField/__snapshots__/TextField.test.tsx.snap
stories/Input/TextFieldStory.tsx

Issue: https://github.com/glints-dev/glints-aries/issues/239
This conversion also refactored the TextField to be a pure controlled component by removing the defaultValue prop. So before publishing this change, we should update all defaultValue to value of TextField in Marketplace and Employers projects.
For example:
```
// in app/components/GlintsJobSearchFilter/FilterOption/FilterSalary.js
<SalaryInput
type="number"
onChange={this.makeSalaryHandler(
DATA_TYPE.maxSalary,
this.props.setMaxSalary
)}
label="Maximum Salary"
defaultValue={salaryFilter.maximum} // should update to value={salaryFilter.maximum}
/>
```

Convert TextField to functional component

---

src/Style/General/AlertStyle.ts

The position of CloseIcon on Alert was wrong.
Before:
After:

Alert: correct close icon position
