src/Item/Item.js, src/Item/index.js, stories/ItemStory.js, stories/index.js
=> feature(Item): Glints Item Component

src/FlexCenter/FlexCenter.js, src/FlexCenter/index.js, src/Style/FlexCenterStyle.js, stories/FlexCenterStory.js, stories/index.js
New utilities component: FlexCenter
=> feat(component): utilities, FlexCenter

src/Style/GlobalStyle.js
=> stye(global): temporary remove heading size

src/Dropdown/Dropdown.js, src/Style/DropdownStyle.js
adding padding to Dropdown Component
=> style(component) adding padding to Dropdown component

src/Slider/LeftArrow.js, src/Slider/RightArrow.js
Next/Prev icon on slider (color change)
=> fix(component): fix slider component next/previous icon

src/Collapsible/Collapsible.js, src/Collapsible/index.js, src/Style/CollapsibleStyle.js, src/index.js, stories/CollapsibleStory.js, stories/index.js
Collapsible Component including the storybook doc
=> feat(component): adding collapsible component

src/JobCard/JobCardHeader.js, src/Style/JobCardStyle.js, stories/JobCardStory.js
adding new props called `jobTitleId` & `companyNameId ` to be passed on to className on each link (Job title link & company name link) in order to tracking needs or styling override
=> feat(props): adding jobTitleId & companyNameId to jobcard Component

src/Button/Button.js, src/Button/PrimaryButton.js
=> refactor(component): Button component refactor. adding id attribute support

src/Style/JobOverviewStyle.js, stories/JobOverviewStory.js
style adjustment for JobOverview component.
=> style(component): JobOverview style adjustment

src/Breadcrumb/Breadcrumb.js, src/Style/BreadcrumbStyle.js, stories/BreadcrumbStory.js
adding new props to breadcrumb component
=> style(component): update breadcrumb. accept bgColor & marginBottomProps

src/Style/Application/JobCardStyle.js
=> - make job card to take container height

src/Style/Display/PopoverStyle.js
- fixed popover modal misalign
=> - fixed popover modal misalign

src/Style/Layout/LayoutStyle.js
- fixed spacing issue in Layout body and Layout header will always stay at the top
=> - fixed header to always stay at the top and add body margin to top

src/Display/Collapsible/Collapsible.js, stories/Display/CollapsibleStory.js
shallowCompare performs a shallow equality check on the current props and nextProps objects as well as the current state and nextState objects
=> fix(collapsible): change default opened state & adding shallow compare

src/Application/JobCard/JobCard.js, stories/Application/JobCardStory.js
Added target prop so that we can control the link opening behaviour. Updated documentation to reflect change. Also included default value in documentation.
=> Add in 1 more prop for job card target behaviour

src/Style/Application/JobCardStyle.js
Removed very specific margin-right style, instead allowing client to decide more detailed styling with regards to button alignment in job card body
=> Removed very specific margin-right style

.gitignore, src/General/Button/PrimaryButton.js, src/Style/General/ButtonStyle.js
Passed defaultProps to PrimaryBtn in PrimaryButton components, and only split out the necessary props to be passed to PrimaryContainer. This was changed because default attributes of the `button` element wasn't received from the parent component due to erroneous props passing. A consequence is that onClick handler is still called despite of disabled being `true`. Other than that, disabled styles are also introduced for PrimaryButton.
Needed for https://trello.com/c/Tb7sdJdo/2239-357-cover-letter-component-on-job-apply-component-4-sp
https://www.w3schools.com/tags/tag_button.asp
Update me after publish so that I can release the card above.
None
=> Logic and styles for disabled button

src/Navigation/NewDropdown/NewDropdown.js, src/Style/Navigation/NewDropdownStyle.js, stories/Navigation/NewDropdownStory.js
- added 4 new props to NewDropdown:
- showHoverLine
- leftIconName 
- dropDownPlacement
- noLineBreak
=> - add new props for newDropDown

src/Navigation/NewDropdown/DropdownItem.js, src/Navigation/NewDropdown/NewDropdown.js
- added new behaviour: 
- Without providing value in NewDropDownItem, will not update Dropdown Label
=> - added new behaviour for newDropDown component

src/Navigation/NewDropdown/DropdownItem.js, src/Navigation/NewDropdown/NewDropdown.js, stories/Navigation/NewDropdownStory.js
- added new props: 
- added dropDownComponentLabel to render NewDropdown component's label in component
=> - added new props in NewDropdown

src/Application/JobCard/JobCard.js, src/Style/Application/JobCardStyle.js
- remove padding in job detail UL
=> - resolved card hover background got cutoff

src/Input/Select/Select.js, stories/Input/SelectStory.js
- change Select storybook code to use StorybookComponent
- change to only check value is undefined
=> - use StorybookComponent for select storybook

src/Input/Textarea/Textarea.js, stories/Input/TextareaStory.js
- fix async change value will not trigger floating label
- change TextArea storybook to use storybook component
=> Fixed textarea label issue 

src/Style/Application/JobOverviewStyle.ts
padding adjustment for jobOverview component
=> style(jobOverview): padding adjustment to jobOverview

src/Input/Select/Select.tsx
src/Input/Select/Select.tsx: check for difference in children instead of just length when updating the state for filterValue
Fixes: https://github.com/glints-dev/glints-aries/issues/104
=> Fix <Select> component filtering old options instead of displaying new options

src/Style/Display/TabsStyle.ts
Refactor tab margins from em to px based on Glints UI
=> <Tabs> Refactor em margins to px based on Glints UI

src/Display/Tabs/Tabs.tsx, src/Style/Display/TabsStyle.ts, src/Utils/StyleConfig.ts, stories/Display/TabsStory.tsx
Adds variant to the Tab component.
**Horizontal**
**Vertical**
**Horizontal (Grey Theme)**
=> Display/Tabs: Add variant to Navigation Tabs and theme to the horizontal navigation tabs

src/Input/Select/Select.test.tsx, src/Input/Select/Select.tsx, src/Input/Select/__snapshots__/Select.test.tsx.snap
- Added unit test
- Fixed bug https://github.com/glints-dev/glints-aries/issues/110
=> <Select> Add unit test and fix bug

src/General/Button/Button.test.tsx, src/General/Button/Button.tsx, src/General/Button/LinkButton.tsx, src/General/Button/__snapshots__/Button.test.tsx.snap, tsconfig.json
- Add unit and snapshot test
- Add `disabled` prop to Button
- Add `className` to LinkButton
- Edit `tsconfig` to allow for es2017 features
=> <Button> Add unit tests and update props

src/Style/General/ButtonStyle.ts
- There was an unexpected gray background on the `DefaultButton` on hover
- It has been removed in this hotfix
=> ButtonStyle: Remove gray background on hover

src/Style/General/TagStyle.ts
=> TagStyle: Add border to default Tag

src/Style/Colors.ts, src/index.ts, stories/Utilities/ColorStory.tsx
https://github.com/glints-dev/glints-aries/issues/148
- Remove some colors from SecondaryColor
- Add colors to Grayscale
Glints UI: https://app.zeplin.io/project/5ba343bf0c399c33db483653/screen/5bbf16daf616cc09a6264519
=> Colors: Update color library

stories/Input/ToggleSwitchStory.tsx
Corrrect `iconOptions` by replacing icon name with icon compoent for `<ToggleSwitch />`
=> Fix error for ToggleSwitchStory

src/Display/Tooltip/Tooltip.tsx
For Issue: https://github.com/glints-dev/glints-aries/issues/108
=> Fix: cannot close tooltip on ios < 13

src/Display/Tooltip/Tooltip.tsx
Relevant Issue: https://github.com/glints-dev/glints-aries/issues/108
=> Fix: should close tooltip when click trigger button

src/Input/Textarea/Textarea.tsx
the event object was not passed to `onBlur`
=> Add event parameter to onBlur

package.json
- GlobalStyle was removed in https://github.com/glints-dev/glints-aries/pull/174
=> Remove GlobalStyle from build scripts

src/Input/Select/Select.tsx, yarn.lock
Related issue: https://github.com/glints-dev/glints-aries/issues/222
=> disable typing Select shouldn't have cursor and open mobile keyboard

src/Input/Select/Select.test.tsx, src/Input/Select/Select.tsx
https://github.com/glints-dev/glints-aries/issues/229
=> Select: Call onOptionClick when enter key is pressed on an option

src/Style/Display/TabsStyle.ts
Fix the styling of the tabs.
The padding and the width are not showing effect due to the missing `;`
=> Tabs: Update the css to fix styling of the tabs button

src/Input/Textarea/Textarea.tsx
=> Textarea: Convert to functional component

src/Display/Modal/Modal.tsx
This MR converts the `Modal` component into a functional component.
I also simplifies the internal state management somewhat.
Closes #244.
=> Modal: Convert to functional component

src/General/Icon/Icon.tsx, src/Style/General/IconStyle.ts, stories/General/IconStory.tsx
Issue: https://github.com/glints-dev/glints-aries/issues/212
=> Make Icon vertical centered by default

src/Input/SearchFilter/SearchFilter.test.tsx, src/Input/SearchFilter/SearchFilter.tsx, stories/Input/SearchFilterStory.tsx
Add inputRef prop to SearchFilter to control the underlying input element
=> SearchFilter: Add inputRef

src/Input/Select/Select.test.tsx, src/Input/Select/Select.tsx, src/Input/Select/SelectList.tsx, src/Input/Select/__snapshots__/Select.test.tsx.snap
=> Select: Convert to functional component
